calib:
  num_samples: 128
  seq_length: 1024
  min_seq_length: 0
  max_seq_length: 0
quant:
  wgts:
    static: true
    dtype: zint4
    group_shapes:
    - - 1
      - -1
    group_scale_dtypes:
    - torch.float16
    compute_dtype: null
    enable_calib_kernel: true
    calib_kernel:
      enable_gptq: true
      gptq:
        damp_percentage: 0.01
        block_size: 128
        num_inv_tries: 250
        hessian_block_size: 512
        include_proj_qkv: true
        include_proj_out: true
        include_proj_1st: true
        include_proj_2nd: true
    enable_calib_range: true
    calib_range:
      objective: OutputsError
      strategy: GridSearch
      granularity: Group
      degree: 2
      element_batch_size: 64
      sample_batch_size: -1
      element_size: 512
      sample_size: -1
      max_shrink: 0.2
      max_expand: 1.0
      num_grids: 80
  ipts:
    static: false
    dtype: sint8
    group_shapes:
    - - 1
      - -1
    group_scale_dtypes:
    - torch.float16
    compute_dtype: null
  opts:
    static: false
    dtype: zint4
    group_shapes:
    - - 1
      - 128
    group_scale_dtypes:
    - torch.float16
    compute_dtype: null
    skip_attn_q: true
  enable_rotation: true
  enable_smooth: true
  smooth:
    enable_xw: true
    xw:
      objective: OutputsError
      strategy: Manual
      granularity: Layer
      degree: 2
      element_batch_size: -1
      sample_batch_size: -1
      element_size: -1
      sample_size: -1
      ranges:
      - - AbsMax
        - AbsMax
      alpha: 0
      beta: 1
      num_grids: 20
      skip_proj_qkv: true
      skip_proj_out: false
      skip_proj_1st: true
      skip_proj_2nd: false
    enable_yx: true
    yx:
      objective: OutputsError
      strategy: Manual
      granularity: Layer
      degree: 2
      element_batch_size: -1
      sample_batch_size: -1
      element_size: -1
      sample_size: -1
      ranges:
      - - AbsMax
        - AbsMax
      alpha: 0.5
      beta: 0.0
      num_grids: 20
      skip_attn_qk: false